# -*- coding: utf-8 -*-
"""Pandas+BI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1nRT8bqFtu2ziDuTccOJwuBPlsKmPmc
"""

import pandas as pd

df = pd.read_csv('train.csv')

df.head()

grouped_data = df.groupby("Region")["Sales"].sum().reset_index()

print(grouped_data)

grouped_data.to_csv("groupedsales.csv", index = False)





